apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.app.namespace }}
data:
  REACT_APP_APIHOSTPORT: api-voteapp.apps.us-west-1.starter.openshift-online.com
  MONGO_CONN_STR: "mongodb://appbackendmongodb:27017/{{.Values.mongodb.mongodbDatabase}}" 
  MONGO_USERNAME: {{ .Values.mongodb.mongodbUsername }}
  MONGO_PASSWORD: {{ .Values.mongodb.mongodbPassword }}