apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.app.name}}-service-fe
  name: {{ template "webserver.fullname" . }}-fe
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.app.containerExposeFe }}
  selector:
    app: {{.Values.app.name}}-fe
  type: {{ .Values.service.type }}
