apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver-deployment
  name: {{ template "webserver.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
  type: {{ .Values.service.type }}
