apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.app.name}}-deployment
  name: {{ template "webserver.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.app.containerExpose }}
  selector:
    app: {{.Values.app.name}}
  type: {{ .Values.service.type }}
